exports.seed = function(knex) {
    return knex('assassins').del()
        .then(() => {
            return knex('assassins').insert([
                {photo: 'http://images3.static-bluray.com/reviews/2752_5.jpg',
                full_name: 'Alexander Duggan', 
                code_name: 'The Jackal', 
                weapon: 'Sniper rifle', 
                contact_info:'jackal@gmail.com', 
                age: 31, 
                price: 45, 
                rating: 7.5, 
                kills: 28, 
                open_contracts: 1,
                hashed_password: bcryptSync.hashSync(`jackal`, 10)
            },
                {photo: 'https://cdn.shopify.com/s/files/1/0153/2051/products/Adam-Caldwell-Anton-Chigur_1024x1024.jpg?v=1515712373' ,
                full_name: 'Anton Chigurh', 
                code_name: 'Old Man', 
                weapon: 'Pneumatic bolt gun', 
                contact_info:'pneujackcity@gmail.com', 
                age: 52, 
                price: 40, 
                rating: 9, 
                kills: 72, 
                open_contracts: 3,
                hashed_password: bcryptSync.hashSync(`nocountry`, 10) 
            },
                {photo: 'http://nextprojection.com/wp-content/uploads/2014/08/Ghost-Dog-1.jpg',
                full_name: '', 
                code_name: 'Ghost Dog', 
                weapon: 'Pistol', 
                contact_info:'ghostdog@gmail.com', 
                age: 28, 
                price: 20, 
                rating: 6.5, 
                kills: 35, 
                open_contracts: 1,
                hashed_password: bcryptSync.hashSync(`ghostcat`, 10) 
            },
                {photo: 'https://timedotcom.files.wordpress.com/2016/07/jason-bourne.jpg',
                full_name: 'Jason Bourne', 
                code_name: '', 
                weapon: 'Parkour', 
                contact_info:'jb@gmail.com', 
                age: 27, 
                price: 25, 
                rating: 7, 
                kills: 48, 
                open_contracts: 3,
                hashed_password: bcryptSync.hashSync(`bourne`, 10) 
            },
                {photo: 'http://ballinnn.com/wp-content/uploads/2018/04/JohnWicksHorribleHair.0.jpg',
                full_name: 'John Wick', 
                code_name: 'Baba Yaga', 
                weapon: 'Lots of guns', 
                contact_info:'babayaga@gmail.com', 
                age: 35, 
                price: 50, 
                rating: 9.5, 
                kills: 433, 
                open_contracts: 6,
                hashed_password: bcryptSync.hashSync(`babayaga`, 10) 
            },
                {photo: 'https://i.pinimg.com/originals/38/80/be/3880be0b24e775a7f47402687421d533.jpg',
                full_name: 'Jules Winnfield', 
                code_name: '', 
                weapon: 'Pistol', 
                contact_info:'bmf@gmail.com', 
                age: 26, 
                price: 15, 
                rating: 6.5, 
                kills: 13, 
                open_contracts: 0,
                hashed_password: bcryptSync.hashSync(`royalewithcheese`, 10) 
            },
                {photo: 'http://i544.photobucket.com/albums/hh356/jelley370/picture108n.png',
                full_name: 'Leon', 
                code_name: 'The Professional', 
                weapon: 'Everything', 
                contact_info:'leon@gmail.com', 
                age: 41, 
                price: 30, 
                rating: 8.5, 
                kills: 87, 
                open_contracts: 3,
                hashed_password: bcryptSync.hashSync(`matilda`, 10)
            },
                {photo: 'https://vignette.wikia.nocookie.net/nikita2010/images/0/0c/Nikita2010_Promos_Season1_0008.jpg/revision/latest?cb=20120827100226&path-prefix=fr',
                full_name: 'Nikita Mears', 
                code_name: 'Nikita', 
                weapon: 'Silenced pistols', 
                contact_info:'nikita@gmail.com', 
                age: 28, 
                price: 30, 
                rating: 7, 
                kills: 32, 
                open_contracts: 1,
                hashed_password: bcryptSync.hashSync(`nikita`, 10)
            },
                {photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw4OBCSwxtka4cYzmBrZHmxedk73vRdVIW1hEUSiOqolnKaGlR',
                full_name: 'Pickle Rick', 
                code_name: 'Solenya', 
                weapon: 'Lasers and office supplies', 
                contact_info:'rsanchez@gmail.com', 
                age: 60, 
                price: 0, 
                rating: 8, 
                kills: 24, 
                open_contracts: 4,
                hashed_password: bcryptSync.hashSync(`morty1`, 10)
            }
            ]);
        });
};
